apiVersion: v1
items:
- apiVersion: kubevirt.io/v1
  kind: VirtualMachine
  metadata:
    annotations:
      vm.kubevirt.io/validations: |
        [
          {
            "name": "minimal-required-memory",
            "path": "jsonpath::.spec.domain.resources.requests.memory",
            "rule": "integer",
            "message": "This VM requires more memory.",
            "min": 1610612736
          }
        ]
      argocd.argoproj.io/sync-wave: "0"
    labels:
      app: rhel9-gitops1-1
      vm.kubevirt.io/template: rhel9-server-small
      vm.kubevirt.io/template.revision: "1"
      vm.kubevirt.io/template.version: v0.14.0
    name: rhel9-gitops1-1
  spec:
    dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: rhel9-gitops1-1
      spec:
        pvc:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi
          storageClassName: # add your storageclass 
        source:
          pvc: 
            name: # add your source 
            namespace: openshift-virtualization-os-images
    running: true 
    template:
      metadata:
        annotations:
          vm.kubevirt.io/flavor: small
          vm.kubevirt.io/os: rhel9
          vm.kubevirt.io/workload: server
        labels:
          kubevirt.io/domain: rhel9-gitops1-1
          kubevirt.io/size: small
          app: techupdate 
      spec:
        domain:
          cpu:
            cores: 1
            sockets: 1
            threads: 1
          devices:
            disks:
            - disk:
                bus: virtio
              name: rhel9-gitops1-1
            - disk:
                bus: virtio
              name: cloudinitdisk
            interfaces:
            - name: default
              masquerade: {}
            - name:  # if you have configured nm state operator, Linux bridge you can name your second interface
              bridge: {}
            networkInterfaceMultiqueue: true
            rng: {}
          machine:
            type: pc-q35-rhel8.4.0
          resources:
            requests:
              memory: 2Gi
        evictionStrategy: LiveMigrate
        networks:
        - name: default
          pod: {}
        - name:  # if you have configured nm state operator, Linux bridge you can name of your network according to NetworkAttachementDefinition.yaml
          multus:
            networkName: # if you have configured nm state operator, Linux bridge you can name of your network according to NetworkAttachementDefinition.yaml
        terminationGracePeriodSeconds: 180
        volumes:
        - dataVolume:
            name: rhel9-gitops1-1
          name: rhel9-gitops1-1
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: # add your user 
              password: # add password
              chpasswd: { expire: False }
          name: cloudinitdisk
        readinessProbe: # this ensures the server is responding on ssh before argocd syncwave 1 starts the ansible workflow
          tcpSocket:
            port: 22
          initialDelaySeconds: 5
          timeoutSeconds: 2
          periodSeconds: 5
kind: List
metadata: {}
